# Generated by Django 5.0.6 on 2024-06-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('input_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_content', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationInputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_id', models.ForeignKey(db_column='communication_id', on_delete=django.db.models.deletion.CASCADE, to='communication.communication')),
            ],
        ),
    ]
