# Generated by Django 5.0.6 on 2024-07-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdata', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='input_content',
            field=models.FileField(upload_to='uploadFiles/'),
        ),
        migrations.DeleteModel(
            name='CommunicationInputData',
        ),
    ]
