# Generated by Django 5.0.6 on 2024-06-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('validation_id', models.AutoField(primary_key=True, serialize=False)),
                ('validation_report', models.FileField(upload_to='uploads/validation/')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_id', models.ForeignKey(db_column='communication_id', on_delete=django.db.models.deletion.CASCADE, to='communication.communication')),
                ('validation_id', models.ForeignKey(db_column='validation_id', on_delete=django.db.models.deletion.CASCADE, to='validation.validation')),
            ],
        ),
    ]
