# Generated by Django 5.0.6 on 2024-07-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_validation_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='validation_report',
            field=models.FileField(null=True, upload_to='validationReports/'),
        ),
        migrations.DeleteModel(
            name='CommunicationValidation',
        ),
    ]
