# Generated by Django 5.0.6 on 2024-07-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_validation_validation_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='user_id',
            new_name='user',
        ),
    ]
