# Generated by Django 5.0.6 on 2024-07-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_rename_user_id_validation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='validated',
            new_name='valid',
        ),
    ]
