# Generated by Django 5.0.6 on 2024-07-25 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_initial'),
        ('ubl', '0003_alter_ubl_ubl_xml_delete_communicationubl'),
        ('user', '0002_user_user_token'),
        ('validation', '0003_alter_validation_validation_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='communication_report',
        ),
        migrations.AddField(
            model_name='communication',
            name='ubl_id',
            field=models.ForeignKey(db_column='ubl_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='ubl.ubl'),
        ),
        migrations.AddField(
            model_name='communication',
            name='validation_id',
            field=models.ForeignKey(db_column='validation_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='validation.validation'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
