# Generated by Django 5.0.6 on 2024-06-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('inputdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationUbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_id', models.ForeignKey(db_column='communication_id', on_delete=django.db.models.deletion.CASCADE, to='communication.communication')),
            ],
        ),
        migrations.CreateModel(
            name='Ubl',
            fields=[
                ('ubl_id', models.AutoField(primary_key=True, serialize=False)),
                ('ubl_content', models.TextField(blank=True, null=True)),
                ('ubl_xml', models.FileField(upload_to='uploads/xml/')),
                ('input_data_id', models.ForeignKey(db_column='input_data_id', on_delete=django.db.models.deletion.CASCADE, to='inputdata.inputdata')),
            ],
        ),
    ]
