# Generated by Django 5.0.6 on 2024-06-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubl', '0001_initial'),
        ('user', '0001_initial'),
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubl',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='ubl',
            name='validation_id',
            field=models.ForeignKey(db_column='validation_id', on_delete=django.db.models.deletion.CASCADE, to='validation.validation'),
        ),
        migrations.AddField(
            model_name='communicationubl',
            name='ubl_id',
            field=models.ForeignKey(db_column='ubl_id', on_delete=django.db.models.deletion.CASCADE, to='ubl.ubl'),
        ),
    ]
