# Generated by Django 5.0.6 on 2024-07-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubl', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubl',
            name='ubl_xml',
            field=models.FileField(upload_to='generatedUbls/'),
        ),
        migrations.DeleteModel(
            name='CommunicationUbl',
        ),
    ]
