import xml.etree.ElementTree as ET


### update content from fronted in xml
def update_xml_content(xml_file_path, updates):
    
    try:
        tree = ET.parse(xml_file_path)
        root = tree.getroot()

        paths = {
            'ID': './/ID/IdentifierContent',
            'IssueDate(Y-M-D)': './/IssueDate/DateContent',
            'DueDate(Y-M-D)': './/DueDate/DateContent',
            'InvoiceTypeCode': './/InvoiceTypeCode/IdentifierContent',
            'Note': './/Note/TextContent',
            'DocumentCurrencyCode': './/DocumentCurrencyCode/IdentifierContent',
            'AccountingCost': './/AccountingCost/TextContent',
            'BuyerReference': './/BuyerReference/TextContent',
            'InvoicePeriodStartDate(Y-M-D)': './/InvoicePeriod/StartDate/DateContent',
            'InvoicePeriodEndDate(Y-M-D)': './/InvoicePeriod/EndDate/DateContent',
            'OrderReferenceID': './/OrderReference/ID/IdentifierContent',
            'OrderReferenceSalesOrderID': './/OrderReference/SalesOrderID/IdentifierContent',
            'BillingReferenceInvoiceDocumentReferenceID': './/BillingReference/InvoiceDocumentReference/ID/IdentifierContent',
            'BillingReferenceInvoiceDocumentReferenceIssueDate': './/BillingReference/InvoiceDocumentReference/IssueDate/DateContent',
            'DespatchDocumentReferenceID': './/DespatchDocumentReference/ID/IdentifierContent',
            'ReceiptDocumentReferenceID': './/ReceiptDocumentReference/ID/IdentifierContent',
            'OriginatorDocumentReferenceID': './/OriginatorDocumentReference/ID/IdentifierContent',
            'ContractDocumentReferenceID': './/ContractDocumentReference/ID/IdentifierContent',
            'SupplierEndpointID': './/AccountingSupplierParty/Party/EndpointID/IdentifierContent',
            'SupplierPartyIdentificationID': './/AccountingSupplierParty/Party/PartyIdentification/ID/IdentifierContent',
            'SupplierPartyName': './/AccountingSupplierParty/Party/PartyName/Name/TextContent',
            'SupplierStreetName': './/AccountingSupplierParty/Party/PostalAddress/StreetName/TextContent',
            'SupplierAdditionalStreetName': './/AccountingSupplierParty/Party/PostalAddress/AdditionalStreetName/TextContent',
            'SupplierCityName': './/AccountingSupplierParty/Party/PostalAddress/CityName/TextContent',
            'SupplierPostalZone': './/AccountingSupplierParty/Party/PostalAddress/PostalZone/TextContent',
            'SupplierCountryIdentificationCode': './/AccountingSupplierParty/Party/PostalAddress/Country/IdentificationCode/IdentifierContent',
            'SupplierCompanyID': './/AccountingSupplierParty/Party/PartyTaxScheme/CompanyID/IdentifierContent',
            'SupplierTaxSchemeID': './/AccountingSupplierParty/Party/PartyTaxScheme/TaxScheme/ID/IdentifierContent',
            'SupplierRegistrationName': './/AccountingSupplierParty/Party/PartyLegalEntity/RegistrationName/TextContent',
            'SupplierCompanyID': './/AccountingSupplierParty/Party/PartyLegalEntity/CompanyID/IdentifierContent',
            'SupplierCompanyLegalForm': './/AccountingSupplierParty/Party/PartyLegalEntity/CompanyLegalForm/TextContent',
            'SupplierContactName': './/AccountingSupplierParty/Party/Contact/Name/TextContent',
            'SupplierContactTelephone': './/AccountingSupplierParty/Party/Contact/Telephone/TextContent',
            'SupplierContactEmail': './/AccountingSupplierParty/Party/Contact/ElectronicMail/TextContent',
            'CustomerEndpointID': './/AccountingCustomerParty/Party/EndpointID/IdentifierContent',
            'CustomerPartyIdentificationID': './/AccountingCustomerParty/Party/PartyIdentification/ID/IdentifierContent',
            'CustomerPartyName': './/AccountingCustomerParty/Party/PartyName/Name/TextContent',
            'CustomerStreetName': './/AccountingCustomerParty/Party/PostalAddress/StreetName/TextContent',
            'CustomerAdditionalStreetName': './/AccountingCustomerParty/Party/PostalAddress/AdditionalStreetName/TextContent',
            'CustomerCityName': './/AccountingCustomerParty/Party/PostalAddress/CityName/TextContent',
            'CustomerPostalZone': './/AccountingCustomerParty/Party/PostalAddress/PostalZone/TextContent',
            'CustomerCountryIdentificationCode': './/AccountingCustomerParty/Party/PostalAddress/Country/IdentificationCode/IdentifierContent',
            'CustomerTaxCompanyID': './/AccountingCustomerParty/Party/PartyTaxScheme/CompanyID/IdentifierContent',
            'CustomerTaxSchemeID': './/AccountingCustomerParty/Party/PartyTaxScheme/TaxScheme/ID/IdentifierContent',
            'CustomerRegistrationName': './/AccountingCustomerParty/Party/PartyLegalEntity/RegistrationName/TextContent',
            'CustomerCompanyID': './/AccountingCustomerParty/Party/PartyLegalEntity/CompanyID/IdentifierContent',
            'CustomerContactName': './/AccountingCustomerParty/Party/Contact/Name/TextContent',
            'CustomerContactTelephone': './/AccountingCustomerParty/Party/Contact/Telephone/TextContent',
            'CustomerContactEmail': './/AccountingCustomerParty/Party/Contact/ElectronicMail/TextContent',
            'PayeePartyIdentificationID': './/PayeeParty/PartyIdentification/ID/IdentifierContent',
            'PayeePartyName': './/PayeeParty/PartyName/Name/TextContent',
            'PayeePartyCompanyID': './/PayeeParty/PartyLegalEntity/CompanyID/IdentifierContent',
            'TaxRepresentativePartyName': './/TaxRepresentativeParty/PartyName/Name/TextContent',
            'TaxRepresentativeStreetName': './/TaxRepresentativeParty/PostalAddress/StreetName/TextContent',
            'TaxRepresentativeAdditionalStreetName': './/TaxRepresentativeParty/PostalAddress/AdditionalStreetName/TextContent',
            'TaxRepresentativeCityName': './/TaxRepresentativeParty/PostalAddress/CityName/TextContent',
            'TaxRepresentativePostalZone': './/TaxRepresentativeParty/PostalAddress/PostalZone/TextContent',
            'TaxRepresentativeCountrySubentity': './/TaxRepresentativeParty/PostalAddress/CountrySubentity/TextContent',
            'TaxRepresentativeAddressLine': './/TaxRepresentativeParty/PostalAddress/AddressLine/Line/TextContent',
            'TaxRepresentativeCountryIdentificationCode': './/TaxRepresentativeParty/PostalAddress/Country/IdentificationCode/IdentifierContent',
            'TaxRepresentativeCompanyID': './/TaxRepresentativeParty/PartyTaxScheme/CompanyID/IdentifierContent',
            'TaxRepresentativeTaxSchemeID': './/TaxRepresentativeParty/PartyTaxScheme/TaxScheme/ID/IdentifierContent',
            'DeliveryActualDeliveryDate(Y-M-D)': './/Delivery/ActualDeliveryDate/DateContent',
            'DeliveryLocationID': './/Delivery/DeliveryLocation/ID/IdentifierContent',
            'DeliveryStreetName': './/Delivery/DeliveryLocation/Address/StreetName/TextContent',
            'DeliveryAdditionalStreetName': './/Delivery/DeliveryLocation/Address/AdditionalStreetName/TextContent',
            'DeliveryCityName': './/Delivery/DeliveryLocation/Address/CityName/TextContent',
            'DeliveryPostalZone': './/Delivery/DeliveryLocation/Address/PostalZone/TextContent',
            'DeliveryCountrySubentity': './/Delivery/DeliveryLocation/Address/CountrySubentity/TextContent',
            'DeliveryAddressLine': './/Delivery/DeliveryLocation/Address/AddressLine/Line/TextContent',
            'DeliveryCountryIdentificationCode': './/Delivery/DeliveryLocation/Address/Country/IdentificationCode/IdentifierContent',
            'DeliveryPartyName': './/Delivery/DeliveryParty/PartyName/Name/TextContent',
            'PaymentMeansCode': './/PaymentMeans/PaymentMeansCode/IdentifierContent',
            'PaymentID': './/PaymentMeans/PaymentID/TextContent',
            'PayeeFinancialAccountID': './/PaymentMeans/PayeeFinancialAccount/ID/IdentifierContent',
            'PayeeFinancialAccountName': './/PaymentMeans/PayeeFinancialAccount/Name/TextContent',
            'PayeeFinancialInstitutionBranchID': './/PaymentMeans/PayeeFinancialAccount/FinancialInstitutionBranch/ID/IdentifierContent',
            'PaymentTermsNote': './/PaymentTerms/Note/TextContent',
            'ChargeIndicator': './/AllowanceCharge/ChargeIndicator/IdentifierContent',
            'AllowanceChargeReasonCode': './/AllowanceCharge/AllowanceChargeReasonCode/IdentifierContent',
            'AllowanceChargeReason': './/AllowanceCharge/AllowanceChargeReason/TextContent',
            'MultiplierFactorNumeric': './/AllowanceCharge/MultiplierFactorNumeric/NumericContent',
            'AllowanceChargeAmount': './/AllowanceCharge/Amount/AmountContent',
            'BaseAmount': './/AllowanceCharge/BaseAmount/AmountContent',
            'TaxCategoryID': './/AllowanceCharge/TaxCategory/ID/IdentifierContent',
            'TaxCategoryPercent': './/AllowanceCharge/TaxCategory/Percent/NumericContent',
            'TaxCategoryTaxSchemeID': './/AllowanceCharge/TaxCategory/TaxScheme/ID/IdentifierContent',
            'TaxAmount': './/TaxTotal/TaxAmount/AmountContent',
            'TaxSubtotalTaxableAmount': './/TaxTotal/TaxSubtotal/TaxableAmount/AmountContent',
            'TaxSubtotalTaxAmount': './/TaxTotal/TaxSubtotal/TaxAmount/AmountContent',
            'TaxSubtotalTaxCategoryID': './/TaxTotal/TaxSubtotal/TaxCategory/ID/IdentifierContent',
            'TaxSubtotalTaxCategoryPercent': './/TaxTotal/TaxSubtotal/TaxCategory/Percent/NumericContent',
            'TaxSubtotalTaxSchemeID': './/TaxTotal/TaxSubtotal/TaxCategory/TaxScheme/ID/IdentifierContent',
            'LineExtensionAmount': './/LegalMonetaryTotal/LineExtensionAmount/AmountContent',
            'TaxExclusiveAmount': './/LegalMonetaryTotal/TaxExclusiveAmount/AmountContent',
            'TaxInclusiveAmount': './/LegalMonetaryTotal/TaxInclusiveAmount/AmountContent',
            'ChargeTotalAmount': './/LegalMonetaryTotal/ChargeTotalAmount/AmountContent',
            'PrepaidAmount': './/LegalMonetaryTotal/PrepaidAmount/AmountContent',
            'PayableAmount': './/LegalMonetaryTotal/PayableAmount/AmountContent',
            'InvoiceLineID': './/InvoiceLine/ID/IdentifierContent',
            'InvoiceLineNote': './/InvoiceLine/Note/TextContent',
            'InvoiceLineInvoicedQuantity': './/InvoiceLine/InvoicedQuantity/NumericContent',
            'InvoiceLineLineExtensionAmount': './/InvoiceLine/LineExtensionAmount/AmountContent',
            'InvoiceLineAccountingCost': './/InvoiceLine/AccountingCost/TextContent',
            'InvoiceLineStartDate(Y-M-D)': './/InvoiceLine/InvoicePeriod/StartDate/DateContent',
            'InvoiceLineEndDate(Y-M-D)': './/InvoiceLine/InvoicePeriod/EndDate/DateContent',
            'InvoiceLineOrderLineReferenceID': './/InvoiceLine/OrderLineReference/LineID/IdentifierContent',
            'InvoiceLineDocumentReferenceID': './/InvoiceLine/DocumentReference/ID/IdentifierContent',
            'InvoiceLineDocumentReferenceTypeCode': './/InvoiceLine/DocumentReference/DocumentTypeCode/IdentifierContent',
            'InvoiceLineItemDescription': './/InvoiceLine/Item/Description/TextContent',
            'InvoiceLineItemName': './/InvoiceLine/Item/Name/TextContent',
            'InvoiceLineBuyersItemIdentificationID': './/InvoiceLine/Item/BuyersItemIdentification/ID/IdentifierContent',
            'InvoiceLineSellersItemIdentificationID': './/InvoiceLine/Item/SellersItemIdentification/ID/IdentifierContent',
            'InvoiceLineStandardItemIdentificationID': './/InvoiceLine/Item/StandardItemIdentification/ID/IdentifierContent',
            'InvoiceLineOriginCountryIdentificationCode': './/InvoiceLine/Item/OriginCountry/IdentificationCode/IdentifierContent',
            'InvoiceLineCommodityClassificationCode': './/InvoiceLine/Item/CommodityClassification/ItemClassificationCode/IdentifierContent',
            'InvoiceLineTaxCategoryID': './/InvoiceLine/Item/ClassifiedTaxCategory/ID/IdentifierContent',
            'InvoiceLineTaxCategoryPercent': './/InvoiceLine/Item/ClassifiedTaxCategory/Percent/NumericContent',
            'InvoiceLineTaxSchemeID': './/InvoiceLine/Item/ClassifiedTaxCategory/TaxScheme/ID/IdentifierContent',
            'InvoiceLinePriceAmount': './/InvoiceLine/Price/PriceAmount/AmountContent',
            'InvoiceLineAllowanceChargeIndicator': './/InvoiceLine/Price/AllowanceCharge/ChargeIndicator/IdentifierContent',
            'InvoiceLineAllowanceChargeAmount': './/InvoiceLine/Price/AllowanceCharge/Amount/AmountContent',
            'InvoiceLineBaseAmount': './/InvoiceLine/Price/AllowanceCharge/BaseAmount/AmountContent'
        }

        for key, new_value in updates.items():
            path = paths.get(key)
            if path:
                element = root.find(path)
                if element is not None:
                    if isinstance(new_value, float):
                        element.text = str(new_value)  # Convert float to string
                    else:
                        element.text = new_value
          
        tree.write(xml_file_path, xml_declaration=True, encoding='utf-8')

    except Exception as e:
        raise e