# Generated by Django 5.0.6 on 2024-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.CharField(default='generate_default_token', max_length=100, unique=True),
        ),
    ]
